### ISSUE TITLE
What difference is that  between api of 0.10.0 and  0.15.1 ?

### ISSUE THREAD

**Issue by goodforever** [chloerei/alipay#86]
Someone  wrote  a wrapper  of alipay for spree based on alipay 0.10.0 
(github.com/formrausch/spree_alipay_forex_trade).
 I want to modify this wrapper to support  alipay 0.15.1,  Can you give me some suggest  ?

**Comment by chloerei** [comment]
The major change between 0.10.0 and 0.15.1 is introducing new class `Alipay::Client` to support new Alipay API. Relationship:

- Alipay::Client - https://openapi.alipay.com/gateway.do
- Alipay::Service - https://mapi.alipay.com/gateway.do

Alipay::Service is old API, I can't find old document any more, but I don't received decline announcement, so it will retain in this gem.

I search Alipay API document for international, found https://global.alipay.com/service/website_split/6 , I'm not sure if it suits you, because Alipay document is confusion. If it is, look like it should use `Alipay::Client`.

Unlike `Alipay::Service` defines many methods for different API, `Alipay::Client` only define simplest method to construct API call, it's more flexible but give the work to you. You should read Alipay document first to know which API you should use, then read source of [client](https://github.com/chloerei/alipay/blob/master/lib/alipay/client.rb) to know which method you should use.

There are some use case in (https://github.com/chloerei/alipay/blob/master/doc/quick_start_en.md). But I have not used international API before, so if you have questions, welcome to post Alipay document links here and discuss which method should be use.
